import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Stairs from "./(components)/Stairs";
import localFont from 'next/font/local';
import { AuthProvider } from "@/context/AuthContext";


const LausanneFont=localFont({
src: './fonts/Lausanne-500.woff2',
variable: '--font-lausanne-500',
weight: '500',
style: 'normal',
})

export const metadata = {
  title: "FitCheck AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${LausanneFont.variable}  antialiased`}
      >
        <Stairs>
 <AuthProvider>

        {children}
 </AuthProvider>
        </Stairs>
      </body>
    </html>
  );
}
